github_apps:
  # examples
  # - name: "example"
  #   description: ""
  #   repo: "owner/repo"
  #   version: 0.1.x
  #   tag_prefix: "v" # 可选, 默认为"v"
  #   package_name: "example"
  #   debian_pattern: "__VERSION__.deb"
  #   redhat_pattern: "__VERSION__.rpm"
  #   binary_name: ""
  #   version_arg: "--version" # 可选, 默认为"--version"
  #   binaries: []
  #   binary_pattern: ""

  - name: "chezmoi"
    description: "Manage your dotfiles across multiple diverse machines, securely."
    repo: "twpayne/chezmoi"
    version: 2.70.5
    binary_name: "chezmoi"
    binary_pattern: "chezmoi___VERSION___linux-musl_amd64.tar.gz"

  - name: "zoxide"
    description: "A smarter cd command. Supports all major shells."
    repo: "ajeetdsouza/zoxide"
    version: 0.9.9
    binary_name: "zoxide"
    binary_pattern: "zoxide-0.9.9-x86_64-unknown-linux-musl.tar.gz"

  - name: "yazi"
    description: "A terminal file viewer"
    repo: "sxyazi/yazi"
    version: 26.5.6
    binary_name: "yazi"
    binary_pattern: "yazi-x86_64-unknown-linux-musl.zip"

  - name: "zellij"
    description: "A terminal workspace with batteries included"
    repo: "zellij-org/zellij"
    version: 0.44.3
    binary_name: "zellij"
    binary_pattern: "zellij-x86_64-unknown-linux-musl.tar.gz"

  - name: "bat"
    description: "A cat(1) clone with wings."
    repo: "sharkdp/bat"
    version: 0.26.1
    binary_name: "bat"
    binary_pattern: "bat-v__VERSION__-x86_64-unknown-linux-musl.tar.gz"

  - name: "fd"
    description: "A simple, fast and user-friendly alternative to 'find'"
    repo: "sharkdp/fd"
    version: 10.4.2
    binary_name: "fd"
    binary_pattern: "fd-v__VERSION__-x86_64-unknown-linux-musl.tar.gz"

  - name: "fzf"
    description: "🌸 A command-line fuzzy finder"
    repo: "junegunn/fzf"
    version: 0.73.1
    binary_name: "fzf"
    binary_pattern: "fzf-__VERSION__-linux_amd64.tar.gz"

  - name: "eza"
    description: "A modern alternative to ls"
    repo: "eza-community/eza"
    version: 0.23.4
    binary_name: "eza"
    binary_pattern: "eza_x86_64-unknown-linux-musl.tar.gz"

  - name: "ripgrep"
    description: "A fast grep replacement"
    repo: "BurntSushi/ripgrep"
    version: 15.1.0
    tag_prefix: ""
    binary_name: "rg"
    binary_pattern: "ripgrep-__VERSION__-x86_64-unknown-linux-musl.tar.gz"

  - name: "jq"
    description: "Command-line JSON processor"
    repo: "jqlang/jq"
    version: 1.8.1
    tag_prefix: "jq-"
    binary_name: "jq"
    binary_pattern: "jq-linux-amd64"

  - name: "yq"
    description: "yq is a portable command-line YAML, JSON, XML, CSV, TOML, HCL and properties processor"
    repo: "mikefarah/yq"
    version: 4.53.3
    binary_name: "yq"
    binary_pattern: "yq_linux_amd64"

  - name: "uv"
    description: "An extremely fast Python package installer and resolver, written in Rust."
    repo: "astral-sh/uv"
    version: 0.11.26
    tag_prefix: ""
    binary_name: "uv"
    binary_pattern: "uv-x86_64-unknown-linux-musl.tar.gz"
